- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import Vpc Varibale
      include_vars: vars/vpc_setup

    - name: Create Prod VPC 
      amazon.aws.ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{VpcCidr}}"
        region: "{{region}}"
        dns_support: true
        dns_hostnames: true
        tenancy: default
        state: "{{state}}"
      register: vpcout
    - name: Create Pub SubNet 1 in Zone 1
      amazon.aws.ec2_vpc_subnet:
        state: "{{state}}"
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone1}}"
        cidr: "{{PubSub1Cidr}}"
        tags:
          Name: Public SubNet 1
      register: pubsub1_out
    - name: Create Pub SubNet 2 in Zone 2
      amazon.aws.ec2_vpc_subnet:
        state: "{{state}}"
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone2}}"
        cidr: "{{PubSub2Cidr}}"
        tags:
          Name: Public Subnet 2
      register: pubsub2_out
    - name: Create Pub SubNet 3 in Zone 3
      amazon.aws.ec2_vpc_subnet:
        state: "{{state}}"
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone3}}"
        cidr: "{{PubSub3Cidr}}"
        tags:
          Name: Public Subnet 3
      register: pubsub3_out
    - name: Create Priv SubNet 1 in Zone 1
      amazon.aws.ec2_vpc_subnet:
        state: "{{state}}"
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone1}}"
        cidr: "{{PrivSub1Cidr}}"
        tags:
          Name: Private Subnet 1
      register: privsub1_out
    - name: Create Priv SubNet 2 in Zone 2
      amazon.aws.ec2_vpc_subnet:
        state: "{{state}}"
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone2}}"
        cidr: "{{PrivSub2Cidr}}"
        tags:
          Name: Private Subnet 2
      register: privsub2_out
    - name: Create Priv SubNet 3 in Zone 3
      amazon.aws.ec2_vpc_subnet:
        state: "{{state}}"
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone3}}"
        cidr: "{{PrivSub3Cidr}}"
        tags:
          Name: Private Subnet 3
      register: privsub3_out
    - name: Create Internet gateway
      ec2_vpc_igw:
        vpc_id: "{{vpcout.vpc.id}}"
        state: "{{state}}"
        region: "{{region}}"
        tags:
          Name: Prod Internet gateway
      register: igw
    - name: Set up public subnet route table
      ec2_vpc_route_table:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        tags:
          Name: Prod Public RT
        subnets:
          - "{{ pubsub1_out.subnet.id }}"
          - "{{ pubsub2_out.subnet.id }}"
          - "{{ pubsub3_out.subnet_id }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ igw.gateway_id }}"
          - dest: ::/0
            gateway_id: "{{ igw.gateway_id }}"
      register: public_route_table